### ISSUE TITLE
Remove Akka snapshots resolver

### ISSUE THREAD

**Issue by ignasi35** [playframework/omnidoc#104]
While on the Milestone/RC cycle for `2.8.0`, in #88 we added the `"akka","snapshots"` resolver on this build. I'm not sure what the purpose was. I think we probably need to remove it.

**Comment by mkurz** [comment]
I removed the resolver now in #188 and 189 because I was getting annoying errors when releasing...
Actually I replaced it with the sonatype snapshot resolver, because that is where the akka snaphots (and in future hopefullly the Play ones as well) live now. I don't think that will do any harm.
