### ISSUE TITLE
Release 2.4.5 for Play - dependency not resolved

### ISSUE THREAD

**Issue by avdv** [playframework/omnidoc#13]
May be just an oversight, but since Play 2.4.5 was already released, the dependency on play-omnidoc 2.4.5 cannot be resolved when using Play 2.4.5 in a project.

(I asked [a question](https://groups.google.com/forum/#!topic/play-framework/C6v7X6_DcB4) about that on the mailing list, but I don't know whether you're subscribed and read this frequently)

**Comment by mkurz** [comment]
I answered on the mailing list. Please wait for an official release announcement.

**Comment by mkurz** [comment]
However - put
```
PlayKeys.playOmnidoc := false
```
in your `build.sbt` for now.

**Comment by Mohamedali10** [comment]
what about play 2.4.3, I'am currently facing it when upgrading from play 2.3 to play 2.4.3 in order to arrive to play 2.7, any advice how to resolve this problem?
